### ISSUE TITLE
Discussion on compression changes

### ISSUE THREAD

**Issue by kruskall** [elastic/go-docappender#102]
Goals:

- avoid aggressive gzip compression (see https://github.com/elastic/go-docappender/issues/94)
- implement document retries without decompressing the whole payload/request
- more efficient compression (optional)

### What changed ?

Before gzip changes             |  After gzip changes
:-------------------------:|:-------------------------:
![before](https://github.com/elastic/go-docappender/assets/99559985/c905cc2d-3fc4-4a36-bb71-d4bd9f178c48)  |  ![after](https://github.com/elastic/go-docappender/assets/99559985/41d7955d-46bf-4203-9c7b-cec30d41aec0)

### Why ?

If events are compressed in batches of size `compressThreshold` we can store the offsets and decompress that specific "container" to avoid decompressing the whole request in memory.
A buffer can also skip the compression completely if the flush timeout is hit and there's not enough data for compression.

Additional optimization technique: if we know there's only 1 event in a "container" we don't even need to decompress at all, we can just copy the compressed bytes since we have the offsets.

### On the compression ratio/efficiency

There was some discussion on how compression worked before. To futher clarify the picture above:
The compression logic happened inside the bulk indexer: https://github.com/elastic/go-docappender/blob/0de03a5e3cfc15a9fa968e21c2af4efd193adf8c/bulk_indexer.go#L174-L184

The event was written to the `gzip.Writer` immediately and we were **not** buffering and then compressing all the events.
(The `gzip.writer` has buffers data internally but it's arbitrary and can't be configured)

Now we write to a buffer compress if we reach a certain size (configurable).

### Testing

The open PR for document retries (https://github.com/elastic/go-docappender/pull/99) has testing to ensure the feature is working as intended.
Additional testing can be performed, see https://github.com/elastic/go-docappender/issues/98

### Infinite retries

IMO this is an issue with the PR so it should be discussed there but we can discuss it more holistically.

In the current implementation events are submitted to the buffer and flushed in the next flush request. There's no max retry setting.

**Comment by axw** [comment]
> The event was written to the gzip.Writer immediately and we were not buffering and then compressing all the events.
> (The gzip.writer has buffers data internally but it's arbitrary and can't be configured)
>
> Now we write to a buffer compress if we reach a certain size (configurable).

gzip uses DEFLATE, which is block-based, and uses a 32KB sliding window dictionary. So why does it matter if we stream data in, compared to buffering and then compressing? If there's an improvement, can you please provide some benchmark comparisons?

**Comment by simitt** [comment]
@kruskall could you provide an update on this?

**Comment by simitt** [comment]
Please provide a bit more details on some of the decisions and the rationale behind them:

> implement document retries without decompressing the whole payload/request

Do I understand correctly that this can be solved by iterating over an array and reading chunks of data without decompressing the whole body into memory?

>We've also decided to discard the optimization to send uncompressed data if the request is too small.

Can you motivate the decision please? I'm not against it, but the rationale should be documented since it had been an open discussion before. 

>Albeit slower, the new approach is a lot simpler.

What does _slower_ mean and can this be quantified?

>The event was written to the gzip.Writer immediately and we were not buffering and then compressing all the events.
(The gzip.writer has buffers data internally but it's arbitrary and can't be configured)
Now we write to a buffer compress if we reach a certain size (configurable).

Are you reverting back to this solution, or are you looking into optimizing, given that you showed that the previous approach wasn't efficient with respect to compression ratio?
