### ISSUE TITLE
benchmarks: automatically run micro benchmarks on PRs

### ISSUE THREAD

**Issue by simitt** [elastic/go-docappender#112]
The go-docappender defines a small set of micro benchmarks: https://github.com/elastic/go-docappender/blob/c8c4e54dbd8820190e465c0811122cb6ffbde24d/appender_bench_test.go#L40 
Given the impact that this code can have on performance of services using the appender, the benchmarks should run on PRs by default. This will create the basis for adding more benchmarks with future changes and seeing results by default.

**Comment by v1v** [comment]
https://github.com/elastic/go-docappender/pull/113 is adding the micro benchmarks on PRs.

There is one minor task I cannot do now: adding the GitHub secret called `APM_TECH_USER_TOKEN`. I don't know who is the owner

**Comment by v1v** [comment]
https://github.com/elastic/go-docappender/pull/114 is one example of running on forked PRs. The auto-tagging works, and then the specific bench-diff GitHub check runs and creates a specific GitHub check with the report
