### ISSUE TITLE
publish metrics for retried documents

### ISSUE THREAD

**Issue by kruskall** [elastic/go-docappender#136]
We're counting the number of retried docs:

https://github.com/elastic/go-docappender/blob/31a3978ba8f93c347ddbf193a9a94131d07f8952/bulk_indexer.go#L66

but we don't publish any metrics about it.

We should add a metric for "retried documents"  similar to what we are doing for Indexed, TooMany, etc.

The counter is already in the response stat and we should be able to publish the metric in https://github.com/elastic/go-docappender/blob/31a3978ba8f93c347ddbf193a9a94131d07f8952/appender.go#L284

**Comment by simitt** [comment]
In addition to the above, the scope of this task should also contain to add the published metrics to our dashboards. Find a good place (potentially the index-service dashboard to add a visualization).

**Comment by inge4pres** [comment]
Is `RetriedDocs` a counter that can be used also to infer how much times documents are retried?
Suppose we're setting `MaxRetry` to 10, is it possible to tell what fraction of those 10 retries are needed for a document to successfully being ingested?
