### ISSUE TITLE
Support OTel metrics

### ISSUE THREAD

**Issue by marclop** [elastic/go-docappender#37]
## Description

Currently, the go-docappender metrics are recorded as unexported `int64` metrics. It would be ideal if we started using an OTel meter to record those metrics and have them exported by the OTel exporter that's configured in the clients.

https://github.com/elastic/go-docappender/blob/b714d6181871607fe9ccb48bfb59ddc0b57318f5/appender.go#L63-L74

We could do this as a breaking change and remove the `Stats()` method, or attempt to do this as a non-breaking change, both have advantages and disadvantages.

### Breaking change

If we do it as a breaking change, we will need to find a way to keep the `apm-server` libbeat metric reporting contract in place.

https://github.com/elastic/apm-server/blob/78ec846c77bffe42553c9e116b1f647a575fee60/internal/beater/beater.go#L716-L770

### Non Breaking change

Another option would be to keep the `Stats()` method and maintain both metric recording mechanisms to avoid creating a breaking change, complexity can be _abstracted_ away, but can't be eliminated.

**Comment by simitt** [comment]
I prefer the _Non-breaking_ option for now. Eventually we would want to introduce the breaking change and completely get rid of `Stats()` in the `go-docappender`, but let's take a staged approach and schedule this for later. 

Also discussed this approach with @axw and @marclop to ensure we are aligned. 

In this iteration, the goal is to:
- write a small abstraction that registers metrics with the `otel Meter` and the existing `atomic` metrics
- use this abstraction everywhere, where we collect metrics
- keep the `Stats()` method unchanged, and don't require changes in apm-server

**Comment by axw** [comment]
Staged approach sounds good. Thanks for keeping it practical @simitt :smile:

For posterity, @marclop and I briefly discussed that we could integrate the OTel metrics with libbeat monitoring by using https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric#NewManualReader. I agree that we can do this in a following step though.
