### ISSUE TITLE
issue: small flush bytes setting has no effect

### ISSUE THREAD

**Issue by kruskall** [elastic/go-docappender#95]
When passing a small flush bytes settings the indexer might ignore it because of gzip internal buffer.

We're currently checking the underlying buffer size:

https://github.com/elastic/go-docappender/blob/7a8fa4d6c6b1774b8b8f4530a6169c369c5931e1/bulk_indexer.go#L159

to flush once we reach the configured "flush bytes" value.

However gzip buffers data internally so if we pass a small request the data will never be written to the buffer until the gzip writer is closed.

The internal gzip buffer size doesn't seem to be configurable so we might need to reject small "flush bytes" values.

**Comment by marclop** [comment]
@kruskall will this be an issue now? After the changes implemented in #91, small writes go directly to the buffer, and not to the gzip writer directly, right?

**Comment by simitt** [comment]
@kruskall can you confirm whether this is still a problem or not?
